#! /bin/bash
for file in $(ls *.c) $(ls *.h)
do
	ci $file
done
for file in $(ls *.c,v) $(ls *.h,v)
do
	co $file
done
remove()
{
	read -n1 -p "Do you want to remove driver (y/n):"
	if [ $REPLY == y ]
	then
		rmmod BlockDev.ko
		echo
		lsmod
		read
		cat /proc/devices
		read
		dmesg
		read
		make clean
	fi
}
insert()
{
	insmod ./modules/BlockDev.ko
	lsmod
	read
	cat /proc/devices
	read 
	dmesg
	read
	remove
}
if ( make )
then
	read -n1 -p "Do you want to insert(y/n):"
	if [ $REPLY == y ]
	then
		echo
		insert
	else 
		echo
		echo "Good Bye"
	fi
else
	echo
	echo "Never mind ..."
fi
read -n1 -p "Do you want to edit file (y/n)"
if [ $REPLY == y ]
then
	for file in $(ls *.c,v) $(ls *.h,v)
	do
		echo
		co -l $file 
  	 done
 else
	 echo
	 echo "Never mined...."
 fi

